# LibraryProject/LibraryProject/settings.py

"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_s8e#%35@19xzzqz!i#dwnki9j0&$q5hiegsx#zgoiavfrnyj9'

# SECURITY WARNING: don't run with debug turned on in production!
# --- SECURITY SETTING: DEBUG (Step 1 of HTTPS objective) ---
# Set to False in production to prevent sensitive information disclosure.
# For development, you might set this to True, but remember to change it back for deployment.
DEBUG = False 

# --- IMPORTANT FOR PRODUCTION ---
# In production, set ALLOWED_HOSTS to your domain names (e.g., ['yourdomain.com', 'www.yourdomain.com'])
# This prevents HTTP Host header attacks.
ALLOWED_HOSTS = [] # Change this to your domain(s) in production


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app',
    # --- SECURITY SETTING: django-csp (Step 4 of previous security objective) ---
    'csp', # Add django-csp to your installed apps
]


MIDDLEWARE = [
    # --- SECURITY SETTING: SecurityMiddleware (Recommended placement at top) ---
    # This middleware provides several security enhancements.
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # --- SECURITY SETTING: CSP Middleware (Step 4 of previous security objective) ---
    # Add django-csp middleware. Place it as high as possible.
    'csp.middleware.CSPMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django Authentication System Settings
LOGIN_REDIRECT_URL = 'relationship_app:book_list'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_URL = 'login'

# Media files (for uploaded user profile photos)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Custom User Model configuration
AUTH_USER_MODEL = 'relationship_app.CustomUser'

# --- ADDITIONAL SECURITY SETTINGS (Steps 1, 2, 3 of HTTPS objective) ---
# Enforce redirecting all HTTP requests to HTTPS.
# Requires your web server (Nginx/Apache) to be set up to handle HTTPS.
SECURE_SSL_REDIRECT = True

# HTTP Strict Transport Security (HSTS) settings.
# Instructs browsers to only access the site via HTTPS for the specified time.
# Set a high value (e.g., 31536000 seconds = 1 year) for production.
SECURE_HSTS_SECONDS = 31536000 # 1 year

# Instructs browsers to apply HSTS policy to all subdomains.
SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# Allows your domain to be preloaded in browser HSTS preload lists.
# Only set to True after verifying your HSTS setup is perfect and permanent.
# Requires SECURE_HSTS_SECONDS to be high.
SECURE_HSTS_PRELOAD = True

# Ensure CSRF cookie is only transmitted over HTTPS. (Step 2)
CSRF_COOKIE_SECURE = True

# Ensure session cookie is only transmitted over HTTPS. (Step 2)
SESSION_COOKIE_SECURE = True

# Prevents content from being served with incorrect MIME types, mitigating XSS risks. (Step 3)
SECURE_CONTENT_TYPE_NOSNIFF = True

# Prevents clickjacking by ensuring your site cannot be embedded in frames. (Step 3)
# 'DENY': No framing allowed. 'SAMEORIGIN': Allowed only from the same origin.
X_FRAME_OPTIONS = 'DENY'

# Enables the X-XSS-Protection header in modern browsers to help prevent XSS attacks. (Step 3)
SECURE_BROWSER_XSS_FILTER = True

# --- Important if behind a reverse proxy (like Nginx/Apache handling SSL) ---
# Tells Django that the request was originally HTTPS, based on the X-Forwarded-Proto header.
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# --- CONTENT SECURITY POLICY (CSP) SETTINGS (from previous security objective) ---
CSP_DEFAULT_SRC = ("'self'",)
CSP_STYLE_SRC = ("'self'", "https://fonts.googleapis.com", "'unsafe-inline'",) # 'unsafe-inline' should be avoided if possible, used for quick setup of inline styles.
CSP_SCRIPT_SRC = ("'self'", "https://code.jquery.com",) # Example: if you use jQuery from a CDN
CSP_IMG_SRC = ("'self'", "data:",) # 'data:' allows data URIs for images
CSP_FONT_SRC = ("'self'", "https://fonts.gstatic.com",)
CSP_CONNECT_SRC = ("'self'",)
CSP_FRAME_SRC = ("'self'",)
# CSP_REPORT_URI = "/csp-report/" # Uncomment and configure if you use CSP violation reporting