# LibraryProject/settings.py

"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# LibraryProject/LibraryProject/settings.py

"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_s8e#%35@19xzzqz!i#dwnki9j0&$q5hiegsx#zgoiavfrnyj9'

# SECURITY WARNING: don't run with debug turned on in production!
# --- SECURITY SETTING: DEBUG (Step 1) ---
# Set to False in production to prevent sensitive information disclosure.
# Keep True for development for detailed error messages.
DEBUG = True 

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app',
    # --- SECURITY SETTING: django-csp (Step 4) ---
    'csp', # Add django-csp to your installed apps
]


MIDDLEWARE = [
    # --- SECURITY SETTING: SecurityMiddleware (Recommended placement at top) ---
    # This middleware provides several security enhancements.
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # --- SECURITY SETTING: CSP Middleware (Step 4) ---
    # Add django-csp middleware. Place it as high as possible.
    'csp.middleware.CSPMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django Authentication System Settings
LOGIN_REDIRECT_URL = 'relationship_app:book_list'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_URL = 'login'

# Media files (for uploaded user profile photos)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Custom User Model configuration
AUTH_USER_MODEL = 'relationship_app.CustomUser'

# --- ADDITIONAL SECURITY SETTINGS (Step 1) ---
# Prevents content from being served with incorrect MIME types.
SECURE_CONTENT_TYPE_NOSNIFF = True

# Prevents the site from being embedded in a <frame>, <iframe>, <embed> tags, etc.
# 'DENY': No framing allowed. 'SAMEORIGIN': Allowed only from the same origin.
X_FRAME_OPTIONS = 'DENY'

# Enables the X-XSS-Protection header for modern browsers.
SECURE_BROWSER_XSS_FILTER = True

# Ensure CSRF and Session cookies are only sent over HTTPS.
# Crucial for production where HTTPS should always be used.
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

# If you want to enforce HTTPS redirects, you might also add:
# SECURE_SSL_REDIRECT = True # Redirects all HTTP requests to HTTPS (requires proper web server config)
# SECURE_HSTS_SECONDS = 31536000 # HSTS header (31536000 seconds = 1 year)
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

# --- CONTENT SECURITY POLICY (CSP) SETTINGS (Step 4) ---
# Default source for content. 'self' means only from your own domain.
CSP_DEFAULT_SRC = ("'self'",)
# Allow styles from your own domain and potentially external CDNs
CSP_STYLE_SRC = ("'self'", "https://fonts.googleapis.com", "'unsafe-inline'",) # 'unsafe-inline' should be avoided if possible, used for quick setup of inline styles.
# Allow scripts from your own domain and potentially external CDNs
CSP_SCRIPT_SRC = ("'self'", "https://code.jquery.com",) # Example: if you use jQuery from a CDN
# Allow images from your own domain
CSP_IMG_SRC = ("'self'", "data:",) # 'data:' allows data URIs for images
# Allow fonts from your own domain and Google Fonts
CSP_FONT_SRC = ("'self'", "https://fonts.gstatic.com",)
# Allow connect-src for AJAX requests
CSP_CONNECT_SRC = ("'self'",)
# If you embed content
CSP_FRAME_SRC = ("'self'",)
# Report violations (optional, but good for debugging CSP)
# CSP_REPORT_URI = "/csp-report/"